import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getAllPosts } from '../lib/notionApi'

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();

  return {
    props: {
      allPosts
    },
    revalidate: 60 // ISRで必要。ここでは、60秒後毎に再更新していく。更新頻度によって変える。
  }
}

const Home: NextPage = ({ allPosts }) => {
  console.log(allPosts)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-gray-500 font-large'>Hoge</h1>
    </div>
  )
}

export default Home
